name: weather_forecast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  http: ^1.3.0
  rxdart: ^0.28.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0
  build_runner: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/weather_icon.png
    - lib/assets/images/weather_forecasts_text.png
    - lib/assets/images/house.jpg
    
 
